"""Structured test positions, generated by the rules and nothing else.

Random ``uint16`` words are useless for testing the embedding gather: the
interesting inputs are the ones the rules actually produce -- a promoted queen
sitting in a pawn slot, the en passant ``special`` bit set on exactly one pawn,
a clock that has been reset by a capture, dead slots scattered through both
halves. So positions come from self-play with uniformly random legal moves,
which is rules only and carries no opinion about chess.

Nothing here is training data and nothing here is a heuristic: this is a source
of diverse *inputs* for correctness tests.
"""

from __future__ import annotations

import torch

from brokefish.env import torch_impl as env

T = 32


def random_positions(n: int, plies: int = 24, seed: int = 0, device: str = "cuda"):
    """``(boards [n,32] int16, control [n] int16, rep [n] uint8)``.

    Each of the ``n`` games walks ``plies`` uniformly random legal moves from the
    start, so the batch spans opening through early middlegame with a spread of
    clocks and captures. Positions that reach a terminal stop advancing and stay
    as they are, which is also worth having in the batch.

    ``rep`` is synthetic. The repetition count is produced by descent-time
    detection in the search (spec 6.3), which does not exist yet, so B2 takes it
    as an argument and this fills it with a plausible spread. When C1 lands, the
    real thing replaces this and the contract does not change.
    """
    gen = torch.Generator(device="cpu").manual_seed(seed)
    boards, control = env.initial_boards(n, device=device)
    mask, _ = env.movegen(boards, control)

    for _ in range(plies):
        legal = env.bitset_to_bool(mask).reshape(n, T * 64)
        counts = legal.sum(dim=1)
        # A terminal position has no legal move; keep it and let it sit.
        live = counts > 0
        if not bool(live.any()):
            break
        r = torch.rand(n, generator=gen).to(device)
        pick = (r * counts.clamp(min=1).float()).long().clamp(max=0x7FFFFFFF)
        # The pick-th set bit of each row, without a host round trip.
        cum = legal.cumsum(dim=1)
        move = (cum > pick[:, None]).float().argmax(dim=1)
        move = torch.where(live, move, torch.zeros_like(move))
        promo = torch.randint(0, 4, (n,), generator=gen).to(device)

        nb, nc, nm, _ = env.play(boards, control, move.to(torch.int64), promo=promo)
        keep = live[:, None]
        boards = torch.where(keep, nb, boards)
        control = torch.where(live, nc, control)
        mask = torch.where(keep, nm, mask)

    # A promoted queen in a pawn slot needs sixty-odd plies to arise by chance,
    # and the embedding gather is a function of the *word*, not of whether the
    # position is reachable -- ``type`` is read from the word and a slot index in
    # 0-7 does not imply a pawn (spec 2.1). So stamp the case in directly on every
    # seventh board rather than paying for the plies.
    live = ((boards >> 11) & 1) == 0
    stamp = (torch.arange(n, device=device) % 7 == 0) & live[:, 3]
    queen = torch.tensor(4 << 6, dtype=torch.int16, device=device)
    boards[:, 3] = torch.where(stamp, (boards[:, 3] & ~(7 << 6)) | queen, boards[:, 3])

    rep = (torch.arange(n, device=device) % 3).to(torch.uint8)
    return boards.contiguous(), control.contiguous(), rep.contiguous()
