"""Confront two engines over HTTP. The arbiter owns the boards; the engines answer.

`python-chess` is the only authority on legality, termination and the result, so
neither engine's rules can influence the score — the point of a neutral referee
between two different stacks.

    POST /move  {"fens": [...], "n": N}  ->  {"moves": [...]}

## The scheduling, which is the whole performance story

⚠️ **Two pools, one per colour assignment, each in lockstep.** Every game in a pool
is at the same ply, so the whole pool wants the *same* engine — one request per ply,
always full width. The first version grouped live games by whose turn it was and
posted twice per round, which double-counted (a game the first engine had just moved
in landed in the second engine's group too) and left the tail paying full price for a
handful of positions. This is `eval/match.py`'s design, which had it right already:
"inside one batch every row is at the same ply, so at any moment every row wants the
same network."

**Slots refill continuously.** A finished game is replaced from the pending pool at
an A-to-move ply, where a fresh game (ply 0, White to move) fits the lockstep
exactly. So requests stay full width until the work actually runs out, instead of
degrading into 2-position calls.

⚠️ Colours are paired: every opening is played twice, once with each engine as White.
Random openings are unbalanced by construction, so without pairing the score measures
who drew the good side. With it, an engine played against itself scores exactly 0.5
whatever the games do — which is this harness's own test.

⚠️ Games unfinished at `--max-plies` are scored **draws, not dropped**
(`evaluation.md` §5.4). Dropping them was measured to remove 35 % of games from a
`t24h-n256` league and inflate the Elo spread, because the games that run long are
precisely the drawn ones.

    python arbiter.py --a http://127.0.0.1:8081 --b http://127.0.0.1:8083 \
        --games 200 --n 128 --width 64
"""
from __future__ import annotations

import argparse
import json
import math
import random
import sys
import time
import urllib.error
import urllib.request

import chess
import chess.pgn


def write_pgn(fh, g, ha, hb, idx: int):
    """Append one finished game. ⚠️ Without this the match is unreviewable.

    Every move is checked legal and every result is python-chess's, so the score is
    sound — but "sound" only rules out *illegal* play. A network fed a wrong board,
    or a policy read through a broken action mapping, emits perfectly legal moves and
    simply loses, and no counter in this harness would say so. The games are the only
    place that shows.
    """
    if fh is None:
        return
    game = chess.pgn.Game.from_board(g.board)
    white = ha if g.a_white else hb
    black = hb if g.a_white else ha
    game.headers["Event"] = "brokefish vs alphagateau"
    game.headers["Round"] = str(idx)
    game.headers["White"] = f"{white.get('engine')} {white.get('ckpt','')}"
    game.headers["Black"] = f"{black.get('engine')} {black.get('ckpt','')}"
    game.headers["FEN"] = g.opening
    game.headers["SetUp"] = "1"
    game.headers["PlyCount"] = str(g.plies)
    # Result from White's point of view, which is PGN's convention; `g.result` is
    # A's, so it has to be flipped when A played Black.
    a_res = g.result
    w_res = a_res if g.a_white else 1.0 - a_res
    game.headers["Result"] = {1.0: "1-0", 0.5: "1/2-1/2", 0.0: "0-1"}[w_res]
    game.headers["Termination"] = (
        "adjudication: ply cap" if g.plies >= g.cap else "normal")
    print(game, file=fh, end="\n\n", flush=True)


def post_moves(url: str, fens, n: int, timeout: float):
    body = json.dumps({"fens": fens, "n": n}).encode()
    req = urllib.request.Request(url.rstrip("/") + "/move", data=body,
                                 headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            out = json.loads(r.read())
    except urllib.error.HTTPError as e:
        raise RuntimeError(f"{url} returned {e.code}: {e.read()[:400]!r}") from None
    moves = out["moves"]
    if len(moves) != len(fens):
        raise RuntimeError(f"{url} returned {len(moves)} moves for {len(fens)} fens")
    return moves


def health(url: str, timeout: float = 60.0):
    try:
        with urllib.request.urlopen(url.rstrip("/") + "/health", timeout=timeout) as r:
            return json.loads(r.read())
    except Exception:  # noqa: BLE001
        return {"engine": "?", "ckpt": "?"}


def openings(count: int, plies: int, seed: int):
    """Distinct, legal, non-terminal positions from uniform random play.

    Generated by the arbiter rather than by either engine: an opening set produced by
    one side's move generator is one more thing that could differ between stacks.
    Self-generated rather than a book also keeps the tabula rasa boundary
    uncomplicated (`evaluation.md` §5.4.1).
    """
    rng = random.Random(seed)
    seen, out, guard = set(), [], 0
    while len(out) < count and guard < count * 400:
        guard += 1
        b = chess.Board()
        for _ in range(plies):
            ms = list(b.legal_moves)
            if not ms:
                break
            b.push(rng.choice(ms))
        if b.is_game_over() or b.fen() in seen:
            continue
        seen.add(b.fen())
        out.append(b.fen())
    if len(out) < count:
        raise RuntimeError(f"only {len(out)} distinct openings after {guard} tries")
    return out


class Game:
    __slots__ = ("board", "a_white", "result", "plies", "opening", "cap")

    def __init__(self, fen: str, a_white: bool, cap: int = 300):
        self.board, self.a_white, self.opening = chess.Board(fen), a_white, fen
        self.result = None
        self.plies = 0
        self.cap = cap

    def score_it(self, max_plies: int) -> bool:
        if self.board.is_game_over(claim_draw=True):
            o = self.board.outcome(claim_draw=True)
            self.result = 0.5 if o.winner is None else \
                (1.0 if (o.winner == chess.WHITE) == self.a_white else 0.0)
            return True
        if self.plies >= max_plies:
            self.result = 0.5
            return True
        return False


def wilson(k: float, n: int, z: float = 1.96):
    if n == 0:
        return 0.0, 0.0, 1.0
    p, d = k / n, 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(max(p * (1 - p) / n + z * z / (4 * n * n), 0.0)) / d
    return p, max(c - h, 0.0), min(c + h, 1.0)


def elo(p: float) -> float:
    p = min(max(p, 1e-4), 1 - 1e-4)
    return 400.0 * math.log10(p / (1 - p))


def run_pool(a_white: bool, fens, args, n_a, n_b, done, t0, ha, hb, pgn):
    """One colour assignment, lockstep, slots refilled from `fens`.

    Returns the finished games. `done` is the shared list so the running score
    printed here covers the whole match and not just this pool.
    """
    pending = list(fens)
    width = min(args.width, len(pending))
    slots = [Game(pending.pop(), a_white, args.max_plies) for _ in range(width)]
    ply = 0
    while slots or pending:
        a_turn = (ply % 2 == 0) == a_white
        # ⚠️ **Retire every ply, refill only on A-to-move plies.** Retiring and
        # refilling together was the bug: a game that ended on A's move stayed in
        # `slots` through B's request, and a finished position has no move to return.
        # The first arbiter had the same fault in a different shape, so it is the
        # *retire* step that must be unconditional; only the *refill* needs the ply
        # parity, because a fresh board is ply 0 with White to move.
        keep = []
        for g in slots:
            if g.result is None:
                keep.append(g)
            else:
                done.append(g)
                write_pgn(pgn, g, ha, hb, len(done))
        slots = keep
        if a_turn:
            while len(slots) < args.width and pending:
                slots.append(Game(pending.pop(), a_white, args.max_plies))
        if not slots:
            break
        url, n = (args.a, n_a) if a_turn else (args.b, n_b)
        moves = post_moves(url, [g.board.fen() for g in slots], n, args.timeout)
        for g, uci in zip(slots, moves):
            try:
                mv = chess.Move.from_uci(uci)
            except ValueError:
                raise RuntimeError(f"{url}: unparseable UCI {uci!r} for "
                                   f"{g.board.fen()}") from None
            if mv not in g.board.legal_moves:
                raise RuntimeError(f"{url}: illegal move {uci!r} for {g.board.fen()}")
            g.board.push(mv)
            g.plies += 1
            g.score_it(args.max_plies)
        ply += 1
        report(done, slots, len(pending), args, t0)
    for g in slots:
        if g.result is not None:
            done.append(g)
            write_pgn(pgn, g, ha, hb, len(done))
    return done


_last = [0.0]


def report(done, slots, pending, args, t0):
    if time.perf_counter() - _last[0] < args.every:
        return
    _last[0] = time.perf_counter()
    n = len(done)
    dt = time.perf_counter() - t0
    if n == 0:
        print(f"  [{dt:6.0f}s] 0/{args.games} finished, {len(slots)} live, "
              f"{pending} pending", flush=True)
        return
    s = sum(g.result for g in done)
    w = sum(1 for g in done if g.result == 1.0)
    d = sum(1 for g in done if g.result == 0.5)
    p, lo, hi = wilson(s, n)
    mean_plies = sum(g.plies for g in done) / n
    eta = dt * (args.games - n) / n
    print(f"  [{dt:6.0f}s] {n:3d}/{args.games} done  A {w}-{d}-{n-w-d}  "
          f"score {p:.3f} [{lo:.3f},{hi:.3f}]  {elo(p):+5.0f} Elo  "
          f"| {len(slots)} live, {pending} pending, {mean_plies:.0f} plies avg "
          f"| eta {eta/60:.0f} min", flush=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--a", required=True)
    ap.add_argument("--b", required=True)
    ap.add_argument("--games", type=int, default=200)
    ap.add_argument("--n", type=int, default=128)
    ap.add_argument("--n-a", type=int, default=None)
    ap.add_argument("--n-b", type=int, default=None)
    ap.add_argument("--width", type=int, default=64, help="games in flight per pool")
    ap.add_argument("--opening-plies", type=int, default=8)
    ap.add_argument("--max-plies", type=int, default=300)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--opening-skip", type=int, default=0,
                    help="drop the first N openings of the seed's list, so that "
                         "segments of one match use disjoint slices of the same set")
    ap.add_argument("--timeout", type=float, default=3600.0)
    ap.add_argument("--every", type=float, default=20.0, help="seconds between reports")
    ap.add_argument("--out", default=None)
    ap.add_argument("--pgn", default=None, help="append every finished game")
    args = ap.parse_args()
    if args.games % 2:
        raise SystemExit("--games must be even: every opening is played twice")
    n_a = args.n_a if args.n_a is not None else args.n
    n_b = args.n_b if args.n_b is not None else args.n

    ha, hb = health(args.a), health(args.b)
    print(f"A = {ha.get('engine')}  {ha.get('ckpt')}   n={n_a}")
    print(f"B = {hb.get('engine')}  {hb.get('ckpt')}   n={n_b}")
    # ⚠️ `--opening-skip` exists so a long match can run in segments and still use the
    # *same* opening set a single run would have used: `openings` is deterministic in
    # (seed, plies) and appends in order, so generating `skip + count` and dropping the
    # first `skip` gives disjoint slices whose union is exactly that seed's list.
    # Added 2026-08-19 because AlphaGateau's server leaks host RAM and must be restarted
    # mid-match; without this, segments would need different seeds and the match would
    # stop being paired with `logs/gate2-h2h-alphagateau.json`, which is seed 0.
    fens = openings(args.games // 2 + args.opening_skip, args.opening_plies,
                    args.seed)[args.opening_skip:]
    print(f"{args.games} games over {len(fens)} openings, width {args.width}, "
          f"max {args.max_plies} plies, reporting every {args.every:.0f}s", flush=True)

    t0 = time.perf_counter()
    done = []
    pgn = open(args.pgn, 'w') if args.pgn else None
    for a_white in (True, False):
        print(f"-- pool: {'A' if a_white else 'B'} as White", flush=True)
        run_pool(a_white, fens, args, n_a, n_b, done, t0, ha, hb, pgn)

    n = len(done)
    s = sum(g.result for g in done)
    w = sum(1 for g in done if g.result == 1.0)
    d = sum(1 for g in done if g.result == 0.5)
    p, lo, hi = wilson(s, n)
    print(f"\nA scores {w}-{d}-{n-w-d}  =  {p:.4f}  [{lo:.4f}, {hi:.4f}] 95% Wilson"
          f"  over {n} games   ({elo(p):+.0f} Elo)")
    print(f"mean plies {sum(g.plies for g in done)/n:.1f}, "
          f"{time.perf_counter()-t0:.0f}s total")
    if args.out:
        json.dump({"a": ha, "b": hb, "n_a": n_a, "n_b": n_b, "games": n,
                   "wins": w, "draws": d, "losses": n - w - d, "score": p,
                   "ci95": [lo, hi], "elo": elo(p), "seed": args.seed,
                   "opening_plies": args.opening_plies, "max_plies": args.max_plies,
                   "mean_plies": sum(g.plies for g in done) / n},
                  open(args.out, "w"), indent=2)
        print(f"wrote {args.out}")


if __name__ == "__main__":
    sys.exit(main())
